### ISSUE TITLE
Not currently working with Cuda 12.8/50 series cards

### ISSUE THREAD

**Issue by Tayyab-H** [derrian-distro/LoRA_Easy_Training_Scripts#290]
Hi, i think it should be a fairly simple fix, but can you please update this to work with 50 series cards, i think the wrong version of CUDA is being used for certain libraries. 

Currently you get a "RuntimeError: No kernel image is available for execution on the device". I DO have CUDA 12.8 installed on my PC with the corresponding pytorch version too, however the install for the lora trainer currently creates its own Venv and uses its own outdated libraries. 

Also on a sidenote, i keep getting a "ModuleNotFoundError: no module named 'triton'". Shouldn't the installer also install triton, because it doesn't seem to be doing that right now. 

Thanks

**Comment by derrian-distro** [comment]
The triton error is standard, it's not important, nor does it hurt anything.
I didn't know that the 50 series didn't have cuda 12.6, as I was unable to get a 5090 myself, so I didn't bother updating it for the new release. I'll get back to you once I have a minute to update the installer to support the 50 series cards

**Comment by Tayyab-H** [comment]
Thanks for getting back so quick! Yeah I managed to pick up a 5080 after one and a half hours of refreshing. 
Anyway, I appreciate the hard work on this, do let me know when it's ready :)

**Comment by derrian-distro** [comment]
Hi! sorry for the delay, I had other things I had to take care of, I have added what I think is a proper check to detect for 50 series cards and install the nightly torch on 12.8 as needed, keep in mind that xformers doesn't support this version of torch, so you will need to use SDPA instead. I have pushed it to dev and until I can confirm it works (of which I can't on my own as I don't have a 50 series card) it will stay there. please give it a try and tell me if that makes it work.

**Comment by Tayyab-H** [comment]
alright, will give it a try now and report back! That was fast i appreciate it :)

**Comment by Tayyab-H** [comment]
ok, it works perfectly, thanks for the quick update! No issues. You do have to turn off xformers and use SDPA. I'll close the issue now :)

**Comment by derrian-distro** [comment]
Great! I'll likely merge it into main once torch is no longer nightly and xformers officially updates to support it
