### ISSUE TITLE
[Windows 10] Trying to get this to work with RTX 5080, after upgrading GPU

### ISSUE THREAD

**Issue by Jatts-Art** [derrian-distro/LoRA_Easy_Training_Scripts#307]
For the past week I've had to go through a ton of trouble trying to get ComfyUI working properly on my new blackwell GPU, mostly following the support thread [here](https://github.com/comfyanonymous/ComfyUI/discussions/6643).

I was finally able to get everything back to working again, but now EasyTrainingScripts and Kohya are the next things I need to try getting up and running properly again. That'll be my focus next, but before I get started I wanted to open up a thread about it too and ask a few questions.

Mainly the problem involves Python and the contents of the venv folder... when starting up the trainer, the CMD prompt gives this error warning:

```
UserWarning:
NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
2025-04-26 16:23:11 WARNING  A matching Triton is not available, some optimizations will not be enabled   __init__.py:61                             Traceback (most recent call last):
                               File "C:\Users\James\Documents\My Projects\Drawing\AI
                             Images\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\Lib\site-packages\
                             xformers\__init__.py", line 57, in _is_triton_available
                                 import triton  # noqa
                                 ^^^^^^^^^^^^^
                             ModuleNotFoundError: No module named 'triton'
C:\Users\James\Documents\My Projects\Drawing\AI Images\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\Lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\James\Documents\My Projects\Drawing\AI Images\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
```

Is it possible for me to have EasyTrainingScripts use a different install of Python somewhere else? Or even use the embeded folder I have for ComfyUI? Or would it be better to try changing the contents of the venv folder? Thanx!

**Comment by derrian-distro** [comment]
it should automatically detect and use the correct version of torch on install, if you are using an older venv from before the upgrade you have to delete the venv in the root and the venv in backend/sd_scripts and re-run the installer

**Comment by Jatts-Art** [comment]
> it should automatically detect and use the correct version of torch on install, if you are using an older venv from before the upgrade you have to delete the venv in the root and the venv in backend/sd_scripts and re-run the installer

I hadn't had the chance to look into this right away, but I had just finished re-cloning a fresh copy from the git today and this is the first error I get when training if I make no changes/deviations from the regular install instructions. Relating to xformers and sd-scripts.

This is also with Python v3.10.9 being my default atm, if that matters at all.

```
Traceback (most recent call last):
  File "C:\Users\James\Documents\My Projects\Drawing\AI Images\EasyTrainingScripts\backend\sd_scripts\library\train_util.py", line 3348, in replace_unet_modules
    import xformers.ops
ModuleNotFoundError: No module named 'xformers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\James\Documents\My Projects\Drawing\AI Images\EasyTrainingScripts\backend\sd_scripts\sdxl_train_network.py", line 229, in <module>
    trainer.train(args)
  File "C:\Users\James\Documents\My Projects\Drawing\AI Images\EasyTrainingScripts\backend\sd_scripts\train_network.py", line 589, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "C:\Users\James\Documents\My Projects\Drawing\AI Images\EasyTrainingScripts\backend\sd_scripts\sdxl_train_network.py", line 58, in load_target_model
    train_util.replace_unet_modules(unet, args.mem_eff_attn, args.xformers, args.sdpa)
  File "C:\Users\James\Documents\My Projects\Drawing\AI Images\EasyTrainingScripts\backend\sd_scripts\library\train_util.py", line 3350, in replace_unet_modules
    raise ImportError("No xformers / xformersがインストールされていないようです")
ImportError: No xformers / xformersがインストールされていないようです
```

I am guessing whichever sd-scripts this one uses isn't quite the same as the most recent Kohya? Within the time ever since making this thread I've managed to get at least Kohya GUI working properly for my 5080 thanks to the discussion [here](https://github.com/bmaltais/kohya_ss/issues/3096), including with xformers.

EDIT: I was able to get it to work! Before I fully show what I had done, there is still one more error message I had gotten which I'd like to confirm if its an issue or not? It relates to triton, although the training is still continuing regardless.

```
W0503 02:08:11.431000 16872 venv\Lib\site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
C:\Users\James\Documents\My Projects\Drawing\AI Images\EasyTrainingScripts\backend\sd_scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\James\Documents\My Projects\Drawing\AI Images\EasyTrainingScripts\backend\sd_scripts\venv\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
C:\Users\James\Documents\My Projects\Drawing\AI Images\EasyTrainingScripts\backend\sd_scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
2025-05-03 02:08:12.655317: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-05-03 02:08:13.553879: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
C:\Users\James\Documents\My Projects\Drawing\AI Images\EasyTrainingScripts\backend\sd_scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
2025-05-03 02:08:15 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:779steps:   steps:  steps:   0%|             | 9/2670 [00:30<2:28:11,  3.34s/it, Average key norm=0.000157, Keys Scaled=steps:   7%|▉             | 180/2670 [07:39<1:45:51,  2.55s/it, Average key norm=0.181, Keys Scaled=1, avr_loss=0.0702]
```

**Comment by Jelosus2** [comment]
The error of xformers is not because of the version of sd scripts, is because there's no version that is compatible with torch uploaded to pytorch registry afaik. The issue you linked makes you install xformers from the official github repository so unless you do it manually you should use SDPA which has about the same performance as xformers but is native from pytorch. As for for the triton error, that's normal in Windows since triton is for Linux.

**Comment by Jatts-Art** [comment]
Ah okay, thanks for the info! And yeah I wasn't super sure about the xformers thing but thats also good to know in case it didn't work for me.

Either way, for those who might ever care about using xformers and may come across this thread, what I had ended up doing was following similar instructions that was used for getting Kohya to work (originally thanks to @evoruta's comment [here](https://github.com/bmaltais/kohya_ss/issues/3096#issuecomment-2837088797)).

>Do the usual clone and install process for [LoRA Easy Training Scripts](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/).
>
>Navigate to LoRA Easy Training Scripts directory and open powershell.
>
>Paste, or type, the following commands:
```
cd .\backend\sd_scripts
py -3.10 -m venv venv
.\venv\Scripts\activate
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
pip3 install bitsandbytes==0.44.0
pip3 install tensorboard
pip3 install tensorflow>=2.16.1
pip3 install onnxruntime-gpu==1.19.2
pip3 install -U accelerate==0.30.0
pip3 install xformers==0.0.30 --index-url https://download.pytorch.org/whl/cu128
pip3 install -U bitsandbytes
```
>Similar to Kohya, I decided to add ' --noverify' into the run.bat file to prevent it from auto-updating, although I am not sure if this part was even needed? Nor if it even works, lmao... but still, I edited it so it looks like this:
```
@echo off

title LoRA Trainer
cd %~dp0
call venv\Scripts\activate
python main.py --noverify
pause

```

Worked right away for me, after all that. If there's anything I said that could be excluded/changed, feel free to mention but yah. 

Thank you for the quick responses as well, very much appreciated!
