### ISSUE TITLE
Error on 50X card

### ISSUE THREAD

**Issue by MartinSyn** [derrian-distro/LoRA_Easy_Training_Scripts#348]
i tried updating PyTorch but that didn't help i am stuck on this. from what i can figure out not even the latest pytorch for cuda 12.9 works and also i am on windows.

D:\Video\Git\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
D:\Video\Git\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\torch\cuda\__init__.py:235: UserWarning:
NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "D:\Video\Git\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
D:\Video\Git\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
2025-10-06 20:12:53 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:779Traceback (most recent call last):
  File "D:\Video\Git\LoRA_Easy_Training_Scripts\backend\sd_scripts\sdxl_train_network.py", line 229, in <module>
    trainer.train(args)
  File "D:\Video\Git\LoRA_Easy_Training_Scripts\backend\sd_scripts\train_network.py", line 1403, in train
    loss = self.process_batch(
  File "D:\Video\Git\LoRA_Easy_Training_Scripts\backend\sd_scripts\train_network.py", line 401, in process_batch
    chunk = self.encode_images_to_latents(args, vae, chunk.to(accelerator.device, dtype=vae_dtype))
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Jelosus2** [comment]
what torch version do you have? you can check by going to `backend/sd_scripts`, open a cmd in that location and executing the following command: `.\venv\Scripts\pip list -v | findstr torch`

**Comment by MartinSyn** [comment]
torch              2.8.0+cu126  d:\video\python\lib\site-packages pip
torchvision        0.23.0+cu126 d:\video\python\lib\site-packages pip

**Comment by Jelosus2** [comment]
For now, be sure to have either python 3.11 or 3.12 installed and that is your active version. After that delete the trainer and clone the repo again but this time appending ` -b dev` to the end of the command and install again

**Comment by MartinSyn** [comment]
it's working thanks a lot. do you know what caused the issue?

**Comment by Jelosus2** [comment]
Wrong python version if you used 3.10 and wrong torch version

**Comment by PheonixAi420** [comment]
> Wrong python version if you used 3.10 and wrong torch version

I did the .\venv\Scripts\pip list -v | findstr torch   and i got C:\StableDiffusion\kohya_ss\LoRA_Easy_Training_Scripts\LoRA_Easy_Training_Scripts\backend\sd_scripts>.\venv\Scripts\pip list -v | findstr torch
came-pytorch               0.1.3                                                                                                             C:\StableDiffusion\kohya_ss\LoRA_Easy_Training_Scripts\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\Lib\site-packages pip
lion-pytorch               0.0.6                                                                                                             C:\StableDiffusion\kohya_ss\LoRA_Easy_Training_Scripts\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\Lib\site-packages pip
pytorch-lightning          1.9.0                                                                                                             C:\StableDiffusion\kohya_ss\LoRA_Easy_Training_Scripts\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\Lib\site-packages pip
pytorch_optimizer          3.1.2                                                                                                             C:\StableDiffusion\kohya_ss\LoRA_Easy_Training_Scripts\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\Lib\site-packages pip
torch                      2.7.0+cu128                                                                                                       C:\StableDiffusion\kohya_ss\LoRA_Easy_Training_Scripts\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\Lib\site-packages pip
torchmetrics               1.8.2                                                                                                             C:\StableDiffusion\kohya_ss\LoRA_Easy_Training_Scripts\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\Lib\site-packages pip
torchvision                0.22.0+cu128                                                                                                      C:\StableDiffusion\kohya_ss\LoRA_Easy_Training_Scripts\LoRA_Easy_Training_Scripts\backend\sd_scripts\venv\Lib\site-packages pip

C:\StableDiffusion\kohya_ss\LoRA_Easy_Training_Scripts\LoRA_Easy_Training_Scripts\backend\sd_scripts>   Does this explain anything as to why its not working @Jelosus2

**Comment by Jelosus2** [comment]
Please stop, I already told you that the program is working as intended, is just your settings that are not optimal, they make the VRAM usage go over shared memory hence why's slow, instead of asking here I would suggest you to join some community that trains on Flux, your issue with the trainer has been solved so now you only need to find the right settings

**Comment by PheonixAi420** [comment]
> Please stop, I already told you that the program is working as intended, is just your settings that are not optimal, they make the VRAM usage go over shared memory hence why's slow, instead of asking here I would suggest you to join some community that trains on Flux, your issue with the trainer has been solved so now you only need to find the right settings

I'm just trying to get help. Thats all. Using the shared memory worked on my 4060 Ti just fine. I have now updated it to use only python 3.12.10 and it loads up but the server wont start. Do you have any info on that? I'm trying to be as nice and understanding as possible.

**Comment by Jelosus2** [comment]
Should I close the issue or you still need something else?

**Comment by MartinSyn** [comment]
you can close this issue, i myself fixed it by reinstalling, pheonixai420 has another problem all together from what i had
